api:
  dashboard: true
  insecure: true   # dashboard sur http://localhost:8080/dashboard/

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: archilan-proxy
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: /certs/acme.json
      dnsChallenge:
        provider: ovh
        resolvers:
          - "213.186.33.99:53"   # DNS OVH pour propagation rapide

log:
  level: INFO

accessLog: {}
